# Generated by Django 6.0.5 on 2026-06-08 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.TextField(verbose_name='История компании')),
                ('image', models.ImageField(upload_to='about/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': '06) О нас',
                'verbose_name_plural': '06) О нас',
            },
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Например: fa-solid fa-shield-halved', max_length=100, verbose_name='Иконка FontAwesome')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': '05) Преимущество',
                'verbose_name_plural': '05) Преимущества',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название (Марка и модель)')),
                ('description', models.TextField(verbose_name='Описание')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('mileage', models.PositiveIntegerField(verbose_name='Пробег (км)')),
                ('fuel_type', models.CharField(max_length=100, verbose_name='Тип топлива')),
                ('transmission', models.CharField(max_length=100, verbose_name='Коробка передач')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет')),
                ('price', models.IntegerField(verbose_name='Цена ($)')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('used', 'С пробегом')], default='used', max_length=10, verbose_name='Статус')),
                ('image', models.ImageField(upload_to='cars/', verbose_name='Главное изображение')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='YouTube видео (ссылка)')),
                ('engine', models.CharField(blank=True, help_text='Например: 2.5 л / 180 л.с', max_length=100, null=True, verbose_name='Двигатель')),
                ('drive', models.CharField(blank=True, help_text='Например: Передний', max_length=100, null=True, verbose_name='Привод')),
                ('wheel', models.CharField(default='Левый', max_length=100, verbose_name='Руль')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Показывать на главной')),
            ],
            options={
                'verbose_name': '03) Автомобиль',
                'verbose_name_plural': '03) Автомобили',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': '07) Сообщение с сайта',
                'verbose_name_plural': '07) Сообщения с сайта',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='hero_image/')),
                ('watsapp', models.CharField(max_length=20)),
                ('telegram', models.CharField(max_length=20)),
                ('instagram', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
            ],
            options={
                'verbose_name': '01) Основные настройки',
                'verbose_name_plural': '01) Основные настройки',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Заголовок (н-р: Авто в наличии)')),
                ('value', models.IntegerField(verbose_name='Значение (число)')),
                ('icon', models.CharField(blank=True, help_text='Например: fa-solid fa-car', max_length=100, verbose_name='Иконка FontAwesome')),
            ],
            options={
                'verbose_name': '02) Статистика',
                'verbose_name_plural': '02) Статистика',
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/gallery/', verbose_name='Дополнительное фото')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': '04) Дополнительное фото',
                'verbose_name_plural': '04) Дополнительные фото',
            },
        ),
    ]
