# Generated by Django 6.0.4 on 2026-06-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='settings',
            name='working_hours',
            field=models.TextField(default='Пн-Пт: 9:00 - 18:00\r\nСб: 10:00 - 15:00', max_length=500, verbose_name='Часы работы'),
        ),
    ]
