# Generated by Django 5.1.15 on 2026-06-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='drive',
            field=models.CharField(blank=True, choices=[('Передний', 'Передний'), ('Задний', 'Задний'), ('Полный', 'Полный')], max_length=100, null=True, verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Бензин', 'Бензин'), ('Дизель', 'Дизель'), ('Электрический', 'Электрический')], max_length=100, verbose_name='Тип топлива'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Автомат', 'Автомат'), ('Механика', 'Механика')], max_length=100, verbose_name='Коробка передач'),
        ),
        migrations.AlterField(
            model_name='car',
            name='wheel',
            field=models.CharField(choices=[('Левый', 'Левый'), ('Правый', 'Правый')], default='Левый', max_length=100, verbose_name='Руль'),
        ),
    ]
