# Generated by Django 6.0.4 on 2026-06-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_car_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='favicons/', verbose_name='Фавикон (иконка сайта)'),
        ),
    ]
