# Generated by Django 5.1.15 on 2026-06-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_car_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='working_hours',
            field=models.TextField(default='Пн-Пт: 9:00 - 18:00\r\nСб: 10:00 - 15:00', max_length=200, verbose_name='Часы работы'),
        ),
    ]
